#!/bin/bash

ANDROID_BUILD_TOP="$(dirname $(realpath "$0"))"
CHECK="$(echo $1 | grep -q check && echo 1)"

function repopick() {
    if [[ "$CHECK" = "1" ]]; then
        echo -n "$1 - " ; ssh lineage-gerrit gerrit query $1 --format=JSON | jq --slurp -r '.[0].status'
    else
        #${ANDROID_BUILD_TOP}/vendor/lineage/build/tools/repopick.py $@
        ${ANDROID_BUILD_TOP}/vendor/lineage/build/tools/repopick.py $@ &
    fi
}

function repopickchain() {
    if [[ "$CHECK" = "1" ]]; then
        echo -n "$1 - " ; ssh lineage-gerrit gerrit query $1 --format=JSON | jq --slurp -r '.[0].status'
    else
        `${ANDROID_BUILD_TOP}/gen_chain $@`
    fi
}

function rc() {
    echo `${ANDROID_BUILD_TOP}/gen_chain $@ | cut -b10-`
}

#
# _examples_
#
# # repo/1
# changes=(
#     2137 # hello
#     `rc 2137` # hello (chain)
# )
# repopick ${changes[@]}
#
# # repo/2
# repopickchain 2137 # hello (chain)
#
# # repo/3
# repopick 2137 # hello
#

# build/make
# repopick 332045 # Don't enforce vintf kernel requirements when building without LTO

# frameworks/base
# repopick 357988 # Set DEFAULT_ADB_ALLOWED_CONNECTION_TIME to 0

# frameworks/av
repopickchain 368311 # Camera: Avoid roundBufferDimensionsNearest also for HAL_PIXEL_FORMAT_BLOB

# frameworks/base
repopickchain 377843 # Screenrecord: Dismiss notification on stop
repopickchain 370006 # Download: Add support to manually pause/resume download
repopickchain 369912 # Support for device specific key handlers
repopickchain 369913 # SystemUI: handle camera launch gesture from keyhandler
repopickchain 369909 # Configurable 0, 90, 180 and 270 degree rotation
repopickchain 369911 # Framework: Volume key cursor control
repopickchain 369914 # Allow adjusting progress on touch events.
repopickchain 369986 # SystemUI: Add API for runtime taskbar config

# frameworks/native
repopickchain 371144 # InputDispatcher: On keypress, deliver keycode to pokeUserActivity

# packages/apps/Settings
repopickchain 376991 # Hide fingerprint settings help if URL is empty
repopickchain 368775 # Allow the user to change the BackupTransport

# packages/apps/SetupWizard
repopickchain 371961 # SetupWizard: Add step for changing theme
repopickchain 378275 # fixup! Simplify biometric detection

# packages/modules/adb
repopickchain 368672 # Squashed import of adb root patches

# packages/services/Telephony
repopickchain 368707 # Telephony: Add ERI configuration for U.S. Cellular

# system/sepolicy
repopickchain 375640 # Label wifi.interface.
repopickchain 368747 # sepolicy: Add sdcard_posix_contextmount_type attribute
repopickchain 375191 # sepolicy: Allow fsck_untrusted to be sys_admin

# system/vold
repopickchain 368773 # vold: fix failing to format zero-ed out SD card

wait
